# Generated by Django 3.0.2 on 2020-03-07 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='isi',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='judul',
            new_name='title',
        ),
    ]
