# Generated by Django 3.0.2 on 2020-03-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200307_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='laporan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('body', models.TextField()),
            ],
        ),
    ]
