# Generated by Django 3.0.2 on 2020-03-07 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_laporan'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='posts',
            new_name='post',
        ),
    ]
